Repository astrohsy/ZETCH, pull requests merged in 2022-09, with the labels that each got.

#7 Add a PostgreSQL DB running on Docker
  demo/README.md
  demo/docker-compose.yml
  demo/pom.xml
  demo/src/main/java/com/example/demo/UserController.java
  demo/src/main/java/com/example/demo/UserRepository.java
  demo/src/main/java/com/example/demo/ZetchUser.java
  demo/src/main/resources/application.properties
Labels: database

#9 ci: Add initial Github Actions workflow for build
  demo/.github/workflows/build.yaml
Labels: integration, In Progress

#17 add swaggerUI dependencies and instructions
  demo/README.md
  demo/pom.xml
Labels: documentation
